version: '3.9'

services:
  djangoservice:
    container_name: ${CONTAINER_NAME_DJANGO}
    build:
      context: .
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - psqlservice
    networks:
      - default

  psqlservice:
    container_name: ${CONTAINER_NAME_PSQL}
    image: postgres:13-alpine
    volumes:
      #- ./data/postgres/data:/var/lib/postgresql/data/
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    # A porta não precisa ser exposta para o host, a menos que você queira acessá-la de fora do Docker
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx_${CONTAINER_NAME_DJANGO}

    volumes:
      - ./data/web/static:/usr/share/nginx/html/static:ro
      - ./data/web/media:/usr/share/nginx/html/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - djangoservice
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
 
