version: '3.9'

services:
  djangoservice:
    container_name: ${CONTAINER_NAME_DJANGO}
    ports:
      - "${DJANGO_PORT_CONTAINER}:8000"
    build:
      context: .
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - psqlservice
    networks:
      - default

  psqlservice:
    container_name: ${CONTAINER_NAME_PSQL}
    image: postgres:13-alpine
    volumes:
      #- ./data/postgres/data:/var/lib/postgresql/data/
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
 